### ISSUE TITLE
Issues in an Apple Silicon M2

### ISSUE THREAD

**Issue by JJ** [osmhpi/pinpoint#14]
It simply says:

```text
No counters available on this system
```

It worked with the M1, though.

**Comment by JJ** [comment]
Is it possible that it's breaking here:

https://github.com/osmhpi/pinpoint/blob/1578db07b1ee30318966d7a2097ee1bb219a9dc8/src/data_sources/AppleM.cpp#L63

?

**Comment by tzwenn** [comment]
Thanks for reporting.
Will try to get a hand on an M2 and investigate.

I recon highlighted line of code will more be a software version detail of IOReport instead of hardware counter depended.

**Comment by tzwenn** [comment]
I just pushed a new version to master, that uses the IOReport channels for `Energy Model`. Although, I didn't fully understand the semantics, the readings are along the lines of what i expect. Maybe you can give it a try.

**Comment by JJ** [comment]
I'm afraid I still get the same result, at least building from master. Should I build from the `m2`. branch maybe?
